package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "zip-iterator-test",
  srcs = ["zip-iterator-test.cc"],
  deps = [
    "//base",
    "//file:file",
    "//file:posix",
    "//stream:zipfile",
    "//util:zip-iterator",
  ],
)

