package(default_visibility = ["//visibility:public"])

load("//tools:embed.bzl", "embed_data")

embed_data(
  name = "app",
  srcs = [
    "external/material.js",
    "external/material.css",
    "external/material-icons.css",
    "external/material-icons.woff2",
    "external/preact.js",
    "image/appicon.ico",
    "lib/docview.js",
    "lib/mdl.js",
    "lib/util.js",
    "style/docview.css",
  ],
)
